from .i9_batch_processing import NODE_CLASS_MAPPINGS as BATCH_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BATCH_DISPLAY_MAPPINGS
from .i9_batch_video_extractor import NODE_CLASS_MAPPINGS as VIDEO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {**BATCH_MAPPINGS, **VIDEO_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**BATCH_DISPLAY_MAPPINGS, **VIDEO_DISPLAY_MAPPINGS}

# Tell ComfyUI this node has web extensions
WEB_DIRECTORY = "./web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
